-- Insert sample businesses for demonstration
INSERT INTO public.businesses (
  seller_id, 
  category_id, 
  business_name, 
  description, 
  industry, 
  location_city, 
  location_state, 
  asking_price, 
  annual_revenue, 
  annual_profit, 
  years_established, 
  number_of_employees, 
  visa_eligible, 
  visa_types, 
  roi_percentage, 
  assets_included, 
  inventory_included, 
  training_provided, 
  financing_available, 
  reason_for_selling, 
  status, 
  featured
) VALUES 
-- Restaurant & Food Service businesses
(
  (SELECT id FROM auth.users LIMIT 1), 
  (SELECT id FROM business_categories WHERE name = 'Restaurants & Food Service' LIMIT 1),
  'Italian Bistro & Wine Bar',
  'Established upscale Italian restaurant with full liquor license, located in prime downtown area. Features authentic Italian cuisine, extensive wine selection, and consistent customer base. Perfect for E-2 visa investors seeking restaurant business with proven track record.',
  'Restaurant',
  'Miami',
  'FL',
  850000,
  1200000,
  180000,
  12,
  25,
  true,
  ARRAY['E-2', 'EB-5'],
  21.2,
  ARRAY['Kitchen Equipment', 'Dining Furniture', 'Wine Inventory', 'POS System'],
  true,
  true,
  true,
  'Owner retirement',
  'approved',
  true
),
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Restaurants & Food Service' LIMIT 1),
  'Artisan Coffee Roastery',
  'Premium coffee roasting operation with established wholesale and retail channels. Includes state-of-the-art roasting equipment, loyal customer base, and growth opportunities in subscription service.',
  'Coffee & Beverages',
  'Austin',
  'TX',
  320000,
  450000,
  85000,
  6,
  8,
  true,
  ARRAY['E-2'],
  26.6,
  ARRAY['Roasting Equipment', 'Retail Fixtures', 'Coffee Inventory', 'Delivery Van'],
  true,
  true,
  false,
  'Expanding to new location',
  'approved',
  false
),

-- Retail & E-commerce businesses  
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Retail & E-commerce' LIMIT 1),
  'Luxury Boutique Chain',
  'High-end fashion boutique with 3 locations in upscale shopping districts. Strong online presence, designer relationships, and affluent customer base. Excellent opportunity for fashion-savvy entrepreneurs.',
  'Fashion Retail',
  'Beverly Hills',
  'CA',
  2100000,
  2800000,
  420000,
  15,
  18,
  true,
  ARRAY['E-2', 'EB-5'],
  20.0,
  ARRAY['Inventory', 'Store Fixtures', 'POS Systems', 'Designer Relationships'],
  true,
  false,
  true,
  'Health reasons',
  'approved',
  true
),
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Retail & E-commerce' LIMIT 1),
  'Organic Pet Supply Store',
  'Thriving organic pet supply business with both physical store and e-commerce platform. Growing market demand, established supplier relationships, and loyal customer base of health-conscious pet owners.',
  'Pet Supplies',
  'Portland',
  'OR',
  280000,
  385000,
  77000,
  4,
  6,
  true,
  ARRAY['E-2'],
  27.5,
  ARRAY['Inventory', 'E-commerce Platform', 'Store Equipment', 'Customer Database'],
  true,
  true,
  false,
  'Relocation',
  'approved',
  false
),

-- Technology & Software businesses
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Technology & Software' LIMIT 1),
  'SaaS Marketing Platform',
  'B2B software-as-a-service platform for small business marketing automation. Recurring revenue model, growing subscriber base, and minimal overhead. Perfect for tech-savvy entrepreneurs.',
  'Software Development',
  'San Francisco',
  'CA',
  1800000,
  1400000,
  560000,
  5,
  12,
  false,
  NULL,
  31.1,
  ARRAY['Software IP', 'Customer Database', 'Development Tools', 'Cloud Infrastructure'],
  false,
  true,
  false,
  'New venture focus',
  'approved',
  true
),

-- Healthcare & Medical businesses
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Healthcare & Medical' LIMIT 1),
  'Physical Therapy Clinic',
  'Well-established physical therapy clinic with excellent reputation and insurance contracts. Modern equipment, experienced staff, and consistent patient flow. Great opportunity in growing healthcare market.',
  'Physical Therapy',
  'Phoenix',
  'AZ',
  650000,
  890000,
  178000,
  8,
  14,
  true,
  ARRAY['E-2', 'EB-5'],
  27.4,
  ARRAY['Medical Equipment', 'Furniture', 'Patient Records System', 'Insurance Contracts'],
  false,
  true,
  true,
  'Career change',
  'approved',
  false
),

-- Manufacturing & Production businesses
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Manufacturing & Production' LIMIT 1),
  'Custom Metal Fabrication Shop',
  'Specialized metal fabrication business serving construction and industrial clients. Well-equipped facility, skilled workforce, and established contracts. Strong demand in growing construction market.',
  'Metal Fabrication',
  'Houston',
  'TX',
  1200000,
  1650000,
  295000,
  18,
  22,
  true,
  ARRAY['E-2', 'EB-5'],
  24.6,
  ARRAY['Manufacturing Equipment', 'Facility Lease', 'Inventory', 'Client Contracts'],
  true,
  true,
  true,
  'Retirement',
  'approved',
  false
),

-- Professional Services businesses
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Professional Services' LIMIT 1),
  'Digital Marketing Agency',
  'Full-service digital marketing agency with diverse client portfolio including local businesses and national brands. Experienced team, proven processes, and recurring revenue streams.',
  'Marketing Services',
  'Chicago',
  'IL',
  750000,
  980000,
  245000,
  7,
  16,
  true,
  ARRAY['E-2'],
  32.7,
  ARRAY['Client Contracts', 'Software Licenses', 'Office Equipment', 'Brand Assets'],
  false,
  true,
  false,
  'Partnership dissolution',
  'approved',
  false
),

-- Automotive businesses
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Automotive' LIMIT 1),
  'Premium Auto Detailing Service',
  'High-end automotive detailing business serving luxury car owners and dealerships. Mobile and fixed location services, premium equipment, and excellent reputation in affluent market.',
  'Auto Services',
  'Scottsdale',
  'AZ',
  195000,
  285000,
  68000,
  3,
  5,
  true,
  ARRAY['E-2'],
  34.9,
  ARRAY['Detailing Equipment', 'Mobile Units', 'Supplies Inventory', 'Client Database'],
  true,
  true,
  false,
  'Family relocation',
  'approved',
  false
),

-- Entertainment & Recreation businesses
(
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM business_categories WHERE name = 'Entertainment & Recreation' LIMIT 1),
  'Indoor Adventure Park',
  'Family entertainment center with climbing walls, arcade games, and party facilities. Popular destination for families and events, strong seasonal performance, and expansion opportunities.',
  'Family Entertainment',
  'Nashville',
  'TN',
  890000,
  1150000,
  207000,
  6,
  18,
  true,
  ARRAY['E-2', 'EB-5'],
  23.3,
  ARRAY['Gaming Equipment', 'Climbing Structures', 'Party Facilities', 'Safety Systems'],
  false,
  true,
  true,
  'Business expansion',
  'approved',
  true
);