-- Phase 1: Content Population
-- Add sample properties across different types
INSERT INTO properties (title, description, property_type, listing_type, price, address, city, state, zip_code, bedrooms, bathrooms, square_feet, lot_size, year_built, agent_id, status, featured, images, property_features) VALUES
('Luxury Downtown Condo', 'Modern luxury condominium in the heart of downtown with stunning city views and premium amenities.', 'Condo', 'sale', 850000, '123 Main Street Unit 1205', 'Miami', 'FL', '33131', 2, 2, 1200, NULL, 2019, NULL, 'active', true, '["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"]', '["City Views", "Gym", "Pool", "Concierge", "Parking"]'),

('Suburban Family Home', 'Beautiful 4-bedroom family home in quiet suburban neighborhood with large backyard and excellent schools.', 'Single Family', 'sale', 475000, '456 Oak Avenue', 'Orlando', 'FL', '32801', 4, 3, 2400, 8500, 2015, NULL, 'active', false, '["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800", "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800"]', '["Large Yard", "Garage", "Updated Kitchen", "Hardwood Floors"]'),

('Beachfront Villa', 'Spectacular oceanfront villa with private beach access and panoramic water views.', 'Single Family', 'sale', 2850000, '789 Ocean Drive', 'Key Biscayne', 'FL', '33149', 5, 4, 4200, 12000, 2018, NULL, 'active', true, '["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"]', '["Ocean Views", "Private Beach", "Pool", "Wine Cellar", "Smart Home"]'),

('Commercial Office Space', 'Prime commercial office space in business district, perfect for growing companies.', 'Commercial', 'lease', 8500, '321 Business Boulevard Suite 500', 'Tampa', 'FL', '33602', NULL, NULL, 3500, NULL, 2010, NULL, 'active', false, '["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"]', '["Conference Rooms", "Parking", "Reception Area", "High-Speed Internet"]'),

('Retail Storefront', 'High-traffic retail space in popular shopping district with excellent visibility.', 'Commercial', 'lease', 12000, '654 Shopping Center Drive', 'Jacksonville', 'FL', '32202', NULL, NULL, 2800, NULL, 2005, NULL, 'active', false, '["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800"]', '["Street Facing", "High Traffic", "Display Windows", "Storage Area"]'),

('Investment Duplex', 'Excellent investment opportunity - duplex with two 2-bedroom units, currently rented.', 'Multi Family', 'sale', 320000, '987 Investment Lane', 'Gainesville', 'FL', '32601', 4, 4, 2000, 6000, 2008, NULL, 'active', false, '["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800"]', '["Rental Income", "Separate Utilities", "Parking", "Laundry Hookups"]'),

('Modern Townhouse', 'Contemporary townhouse with open floor plan and rooftop terrace in trendy neighborhood.', 'Townhouse', 'sale', 625000, '147 Modern Way', 'Fort Lauderdale', 'FL', '33301', 3, 2.5, 1800, 1200, 2020, NULL, 'active', true, '["https://images.unsplash.com/photo-1605276373954-0c4a0dac5cc0?w=800"]', '["Rooftop Terrace", "Open Floor Plan", "Modern Finishes", "Garage"]'),

('Luxury Penthouse', 'Exclusive penthouse with 360-degree city views and premium finishes throughout.', 'Condo', 'sale', 1950000, '555 Skyline Tower Penthouse', 'Miami', 'FL', '33131', 3, 3, 2800, NULL, 2021, NULL, 'active', true, '["https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800"]', '["360 Views", "Private Elevator", "Terrace", "Premium Finishes", "Concierge"]'),

('Starter Home', 'Perfect starter home for first-time buyers in established neighborhood with good schools.', 'Single Family', 'sale', 285000, '852 Maple Street', 'Tallahassee', 'FL', '32301', 3, 2, 1400, 5500, 2005, NULL, 'active', false, '["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"]', '["Move-in Ready", "Fenced Yard", "Updated Appliances", "Quiet Street"]'),

('Warehouse Space', 'Large industrial warehouse with loading docks and office space, perfect for distribution.', 'Industrial', 'lease', 15000, '741 Industrial Parkway', 'Tampa', 'FL', '33619', NULL, NULL, 25000, 50000, 1995, NULL, 'active', false, '["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800"]', '["Loading Docks", "Office Space", "High Ceilings", "Truck Access"]'),

('Rental Apartment', 'Spacious 2-bedroom apartment in desirable location with modern amenities.', 'Apartment', 'rent', 2200, '963 Rental Avenue Apt 3B', 'St. Petersburg', 'FL', '33701', 2, 2, 1100, NULL, 2016, NULL, 'active', false, '["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"]', '["Pool", "Fitness Center", "In-unit Laundry", "Balcony"]'),

('Golf Course Home', 'Stunning home on prestigious golf course with fairway views and club membership.', 'Single Family', 'sale', 1125000, '159 Fairway Drive', 'Naples', 'FL', '34102', 4, 3, 3200, 10000, 2012, NULL, 'active', true, '["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800"]', '["Golf Course Views", "Club Membership", "Pool", "Premium Location"]'),

('Historic Charm', 'Beautifully restored historic home with original character and modern updates.', 'Single Family', 'sale', 525000, '357 Heritage Boulevard', 'St. Augustine', 'FL', '32084', 3, 2, 2200, 7500, 1925, NULL, 'active', false, '["https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800"]', '["Historic Character", "Restored Features", "Modern Updates", "Large Lot"]'),

('Medical Office', 'Professional medical office space with multiple exam rooms and reception area.', 'Commercial', 'lease', 18000, '753 Medical Plaza Drive', 'Sarasota', 'FL', '34236', NULL, NULL, 4200, NULL, 2008, NULL, 'active', false, '["https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800"]', '["Exam Rooms", "Reception Area", "Medical Equipment Ready", "Parking"]'),

('Lake House Retreat', 'Peaceful lakefront home perfect for weekend getaways or full-time living.', 'Single Family', 'sale', 675000, '951 Lake Shore Drive', 'Winter Haven', 'FL', '33880', 3, 2, 1900, 15000, 2010, NULL, 'active', true, '["https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"]', '["Lakefront", "Dock", "Peaceful Setting", "Nature Views"]');

-- Add sample agent profiles with complete information
INSERT INTO employee_profiles (user_id, full_name, email, position, department_id, hire_date, is_active, employee_id, years_experience, current_skill_level, career_goals) VALUES
(gen_random_uuid(), 'Sarah Johnson', 'sarah.johnson@gruposineva.com', 'Senior Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2020-01-15', true, 'AGT001', 8, 'Expert', 'Residential and luxury property specialist serving Miami-Dade and Broward counties'),
(gen_random_uuid(), 'Michael Rodriguez', 'michael.rodriguez@gruposineva.com', 'Commercial Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2019-03-20', true, 'AGT002', 12, 'Expert', 'Commercial property expert specializing in office buildings and retail spaces in Central Florida'),
(gen_random_uuid(), 'Emily Chen', 'emily.chen@gruposineva.com', 'Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2021-06-10', true, 'AGT003', 5, 'Intermediate', 'First-time homebuyer specialist serving Orlando and surrounding areas'),
(gen_random_uuid(), 'David Thompson', 'david.thompson@gruposineva.com', 'Senior Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2018-09-05', true, 'AGT004', 15, 'Expert', 'Luxury waterfront property specialist in Tampa Bay and Sarasota'),
(gen_random_uuid(), 'Lisa Martinez', 'lisa.martinez@gruposineva.com', 'Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2022-02-14', true, 'AGT005', 3, 'Beginner', 'Investment property specialist helping clients build wealth through real estate in Jacksonville'),
(gen_random_uuid(), 'Robert Wilson', 'robert.wilson@gruposineva.com', 'Commercial Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2017-11-30', true, 'AGT006', 18, 'Expert', 'Industrial and warehouse property expert serving statewide commercial clients'),
(gen_random_uuid(), 'Amanda Foster', 'amanda.foster@gruposineva.com', 'Senior Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2019-08-22', true, 'AGT007', 10, 'Expert', 'Relocation specialist helping families transition to Florida from out of state'),
(gen_random_uuid(), 'James Park', 'james.park@gruposineva.com', 'Real Estate Agent', (SELECT id FROM departments WHERE name = 'Sales' LIMIT 1), '2020-12-01', true, 'AGT008', 6, 'Intermediate', 'New construction and development specialist in Southwest Florida');

-- Add sample leads for testing CRM functionality
INSERT INTO leads (lead_source, lead_status, priority, contact_info, estimated_value, notes, agent_id, property_id, last_contact_at) VALUES
('Website Contact Form', 'new', 'high', '{"name": "John Smith", "email": "john.smith@email.com", "phone": "(555) 123-4567", "preferred_contact": "phone"}', 450000, 'Interested in 3-4 bedroom homes in Orlando area, budget up to $500k, looking to buy within 3 months', (SELECT id FROM employee_profiles WHERE email = 'emily.chen@gruposineva.com' LIMIT 1), NULL, NOW() - INTERVAL '2 hours'),
('Referral', 'qualified', 'high', '{"name": "Maria Garcia", "email": "maria.garcia@email.com", "phone": "(555) 234-5678", "preferred_contact": "email"}', 850000, 'Looking for luxury condo in Miami Beach, cash buyer, needs to close quickly', (SELECT id FROM employee_profiles WHERE email = 'sarah.johnson@gruposineva.com' LIMIT 1), (SELECT id FROM properties WHERE title = 'Luxury Downtown Condo' LIMIT 1), NOW() - INTERVAL '1 day'),
('Social Media', 'contacted', 'medium', '{"name": "Robert Lee", "email": "robert.lee@email.com", "phone": "(555) 345-6789", "preferred_contact": "email"}', 25000, 'Small business owner looking for retail space in Jacksonville, 2000-3000 sq ft', (SELECT id FROM employee_profiles WHERE email = 'michael.rodriguez@gruposineva.com' LIMIT 1), NULL, NOW() - INTERVAL '3 days'),
('Walk-in', 'new', 'medium', '{"name": "Jennifer Davis", "email": "jennifer.davis@email.com", "phone": "(555) 456-7890", "preferred_contact": "phone"}', 320000, 'First-time homebuyer, pre-approved for $350k, interested in starter homes', (SELECT id FROM employee_profiles WHERE email = 'emily.chen@gruposineva.com' LIMIT 1), (SELECT id FROM properties WHERE title = 'Starter Home' LIMIT 1), NOW() - INTERVAL '5 hours'),
('Google Ads', 'qualified', 'high', '{"name": "Thomas Anderson", "email": "thomas.anderson@email.com", "phone": "(555) 567-8901", "preferred_contact": "email"}', 2500000, 'Investor looking for waterfront properties, has $3M budget, multiple property interest', (SELECT id FROM employee_profiles WHERE email = 'david.thompson@gruposineva.com' LIMIT 1), (SELECT id FROM properties WHERE title = 'Beachfront Villa' LIMIT 1), NOW() - INTERVAL '12 hours'),
('Phone Call', 'nurturing', 'low', '{"name": "Susan Brown", "email": "susan.brown@email.com", "phone": "(555) 678-9012", "preferred_contact": "phone"}', 180000, 'Looking to downsize, timeline flexible, interested in condos or smaller homes', (SELECT id FROM employee_profiles WHERE email = 'amanda.foster@gruposineva.com' LIMIT 1), NULL, NOW() - INTERVAL '1 week'),
('Email Campaign', 'contacted', 'medium', '{"name": "Michael Johnson", "email": "michael.johnson@email.com", "phone": "(555) 789-0123", "preferred_contact": "email"}', 75000, 'Commercial lease inquiry for warehouse space, distribution business, needs loading docks', (SELECT id FROM employee_profiles WHERE email = 'robert.wilson@gruposineva.com' LIMIT 1), (SELECT id FROM properties WHERE title = 'Warehouse Space' LIMIT 1), NOW() - INTERVAL '2 days'),
('Website Chat', 'new', 'high', '{"name": "Catherine Williams", "email": "catherine.williams@email.com", "phone": "(555) 890-1234", "preferred_contact": "text"}', 1200000, 'Looking for luxury home on golf course, specific about location and amenities', (SELECT id FROM employee_profiles WHERE email = 'david.thompson@gruposineva.com' LIMIT 1), (SELECT id FROM properties WHERE title = 'Golf Course Home' LIMIT 1), NOW() - INTERVAL '30 minutes');

-- Update properties to link with agents
UPDATE properties SET agent_id = (SELECT id FROM employee_profiles WHERE email = 'sarah.johnson@gruposineva.com' LIMIT 1) WHERE title IN ('Luxury Downtown Condo', 'Luxury Penthouse');
UPDATE properties SET agent_id = (SELECT id FROM employee_profiles WHERE email = 'michael.rodriguez@gruposineva.com' LIMIT 1) WHERE title IN ('Commercial Office Space', 'Retail Storefront', 'Warehouse Space', 'Medical Office');
UPDATE properties SET agent_id = (SELECT id FROM employee_profiles WHERE email = 'emily.chen@gruposineva.com' LIMIT 1) WHERE title IN ('Suburban Family Home', 'Starter Home', 'Modern Townhouse');
UPDATE properties SET agent_id = (SELECT id FROM employee_profiles WHERE email = 'david.thompson@gruposineva.com' LIMIT 1) WHERE title IN ('Beachfront Villa', 'Golf Course Home', 'Lake House Retreat');
UPDATE properties SET agent_id = (SELECT id FROM employee_profiles WHERE email = 'lisa.martinez@gruposineva.com' LIMIT 1) WHERE title IN ('Investment Duplex', 'Rental Apartment');
UPDATE properties SET agent_id = (SELECT id FROM employee_profiles WHERE email = 'amanda.foster@gruposineva.com' LIMIT 1) WHERE title IN ('Historic Charm');