-- Insert sample properties for testing
INSERT INTO public.properties (
  agent_id,
  title,
  description,
  property_type,
  listing_type,
  price,
  address,
  city,
  state,
  zip_code,
  bedrooms,
  bathrooms,
  square_feet,
  lot_size,
  year_built,
  property_features,
  images,
  virtual_tour_url,
  status,
  featured
) VALUES 
(
  (SELECT id FROM employee_profiles LIMIT 1),
  'Luxury Downtown Condo',
  'Stunning downtown condominium with panoramic city views. Perfect for professionals and investors.',
  'residential',
  'for_sale',
  850000.00,
  '123 Main Street, Unit 2504',
  'Houston',
  'TX',
  '77002',
  2,
  2.0,
  1200,
  0.0,
  2020,
  '["Granite Countertops", "Stainless Steel Appliances", "Balcony", "Gym Access", "Concierge"]'::jsonb,
  '["https://via.placeholder.com/400x300", "https://via.placeholder.com/400x300"]'::jsonb,
  'https://virtual-tour.example.com/luxury-condo',
  'active',
  true
),
(
  (SELECT id FROM employee_profiles LIMIT 1),
  'Modern Family Home',
  'Beautiful 4-bedroom family home in prestigious neighborhood with excellent schools.',
  'residential',
  'for_sale',
  650000.00,
  '456 Oak Avenue',
  'Austin',
  'TX',
  '78701',
  4,
  3.5,
  2800,
  0.25,
  2018,
  '["Hardwood Floors", "Updated Kitchen", "Swimming Pool", "Large Backyard", "Garage"]'::jsonb,
  '["https://via.placeholder.com/400x300", "https://via.placeholder.com/400x300"]'::jsonb,
  null,
  'active',
  false
),
(
  (SELECT id FROM employee_profiles LIMIT 1),
  'Prime Commercial Office',
  'Premium office space in the heart of the business district. Perfect for growing companies.',
  'commercial',
  'for_lease',
  8500.00,
  '789 Business Plaza, Suite 500',
  'Dallas',
  'TX',
  '75201',
  null,
  2.0,
  3500,
  0.0,
  2019,
  '["Modern Finishes", "Conference Rooms", "Parking Included", "High-Speed Internet", "Security"]'::jsonb,
  '["https://via.placeholder.com/400x300", "https://via.placeholder.com/400x300"]'::jsonb,
  null,
  'active',
  true
),
(
  (SELECT id FROM employee_profiles LIMIT 1),
  'Investment Property Package',
  'Excellent investment opportunity with guaranteed returns. Perfect for E-2 visa investors.',
  'business',
  'investment',
  1200000.00,
  '321 Investment Drive',
  'San Antonio',
  'TX',
  '78201',
  null,
  null,
  5000,
  1.0,
  2017,
  '["Established Business", "Guaranteed ROI", "Management Included", "E-2 Visa Eligible", "Profitable"]'::jsonb,
  '["https://via.placeholder.com/400x300", "https://via.placeholder.com/400x300"]'::jsonb,
  null,
  'active',
  true
),
(
  (SELECT id FROM employee_profiles LIMIT 1),
  'Starter Home Special',
  'Perfect first home for young families. Great value in up-and-coming neighborhood.',
  'residential',
  'for_sale',
  280000.00,
  '654 Maple Street',
  'Fort Worth',
  'TX',
  '76101',
  3,
  2.0,
  1450,
  0.15,
  2015,
  '["Recently Renovated", "New HVAC", "Fenced Yard", "Near Schools", "Move-in Ready"]'::jsonb,
  '["https://via.placeholder.com/400x300", "https://via.placeholder.com/400x300"]'::jsonb,
  null,
  'active',
  false
);