// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbvvydecbbnuprmhpfvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidnZ5ZGVjYmJudXBybWhwZnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTUzMDQsImV4cCI6MjA3MTAzMTMwNH0.IhEcUgjeNsZn-mmaFRoAtERC_jtxmG85HU8erDt79ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});